jwt:
  secret: oiasjfoiasj8asd23124!####9u203i49jioh!$$
  expirationInMinutes: 1500
  issuer: tvz

spring:
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: false

  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/tvz
    username: tvzadmin
    password: 'tvz'